from models import Recipe, Ingredient

# Sample recipe data
recipes = [
    Recipe(
        id=1,
        name="Spaghetti Carbonara",
        cuisine="Italian",
        difficulty=2,
        prep_time=25,
        ingredients=[
            Ingredient(name="spaghetti", amount=400, unit="g"),
            Ingredient(name="pancetta", amount=150, unit="g"),
            Ingredient(name="egg yolks", amount=4, unit="units"),
            Ingredient(name="parmesan cheese", amount=50, unit="g"),
            Ingredient(name="black pepper", amount=1, unit="tsp"),
            Ingredient(name="salt", amount=0.5, unit="tsp"),
        ],
        instructions="1. Cook pasta. 2. Fry pancetta. 3. Mix eggs and cheese. 4. Combine all ingredients.",
    ),
    Recipe(
        id=2,
        name="Chicken Curry",
        cuisine="Indian",
        difficulty=3,
        prep_time=45,
        ingredients=[
            Ingredient(name="chicken breast", amount=500, unit="g"),
            Ingredient(name="onion", amount=1, unit="unit"),
            Ingredient(name="garlic", amount=3, unit="cloves"),
            Ingredient(name="curry powder", amount=2, unit="tbsp"),
            Ingredient(name="coconut milk", amount=400, unit="ml"),
            Ingredient(name="vegetable oil", amount=2, unit="tbsp"),
            Ingredient(name="salt", amount=1, unit="tsp"),
        ],
        instructions="1. Dice chicken. 2. Sauté onions and garlic. 3. Add chicken and spices. 4. Pour in coconut milk and simmer.",
    ),
    Recipe(
        id=3,
        name="Caesar Salad",
        cuisine="American",
        difficulty=1,
        prep_time=15,
        ingredients=[
            Ingredient(name="romaine lettuce", amount=1, unit="head"),
            Ingredient(name="croutons", amount=100, unit="g"),
            Ingredient(name="parmesan cheese", amount=30, unit="g"),
            Ingredient(name="caesar dressing", amount=60, unit="ml"),
            Ingredient(name="chicken breast", amount=200, unit="g"),
            Ingredient(name="black pepper", amount=0.5, unit="tsp"),
        ],
        instructions="1. Wash and chop lettuce. 2. Grill chicken and slice. 3. Toss all ingredients with dressing.",
    ),
    Recipe(
        id=4,
        name="Chocolate Chip Cookies",
        cuisine="American",
        difficulty=2,
        prep_time=60,
        ingredients=[
            Ingredient(name="all-purpose flour", amount=280, unit="g"),
            Ingredient(name="butter", amount=225, unit="g"),
            Ingredient(name="white sugar", amount=100, unit="g"),
            Ingredient(name="brown sugar", amount=165, unit="g"),
            Ingredient(name="eggs", amount=2, unit="units"),
            Ingredient(name="vanilla extract", amount=1, unit="tsp"),
            Ingredient(name="baking soda", amount=1, unit="tsp"),
            Ingredient(name="chocolate chips", amount=300, unit="g"),
            Ingredient(name="salt", amount=0.5, unit="tsp"),
        ],
        instructions="1. Cream butter and sugars. 2. Add eggs and vanilla. 3. Mix in dry ingredients. 4. Fold in chocolate chips. 5. Bake at 350°F for 10-12 minutes.",
    ),
    Recipe(
        id=5,
        name="Beef Stir Fry",
        cuisine="Chinese",
        difficulty=3,
        prep_time=30,
        ingredients=[
            Ingredient(name="beef sirloin", amount=400, unit="g"),
            Ingredient(name="bell peppers", amount=2, unit="units"),
            Ingredient(name="broccoli", amount=200, unit="g"),
            Ingredient(name="soy sauce", amount=3, unit="tbsp"),
            Ingredient(name="garlic", amount=2, unit="cloves"),
            Ingredient(name="ginger", amount=1, unit="tbsp"),
            Ingredient(name="vegetable oil", amount=2, unit="tbsp"),
            Ingredient(name="sesame oil", amount=1, unit="tsp"),
        ],
        instructions="1. Slice beef thinly. 2. Chop vegetables. 3. Stir-fry beef, then remove. 4. Stir-fry vegetables. 5. Combine with sauce and beef.",
    ),
]
